spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/devdb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          aut: true
          starttls:
            enable: true
  jackson:
    serializable:
      fail-on-empty-beans: false