spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: psw1234
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: almacaciulanegrea@gmail.com
    password: cmcabrgwxamluemb
    properties:
      mail:
        smtp:
          aut: true
          starttls:
            enable: true
  jackson:
    serializable:
      fail-on-empty-beans: false
